import {test,expect} from '@playwright/test';
test('month, day, navigation, details and empty day',async({page},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');
 await expect(page.getByRole('heading',{name:'2026年 10月'})).toBeVisible();
 await expect(page.locator('.day-cell')).toHaveCount(42);
 await expect(page.locator('.event-card')).toHaveCount(5);
 await expect(page.getByText('次の予定')).toBeVisible();
 const size=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));expect(size.scroll).toBeLessThanOrEqual(size.width);
 await page.screenshot({path:`test-results/calendar-${info.project.name}.png`,fullPage:true});
 await page.getByRole('button',{name:/夕方の散歩/}).click();
 await expect(page.getByRole('dialog')).toBeVisible();
 await expect(page.locator('.description')).toContainText('<script>');
 await page.getByRole('button',{name:'詳細を閉じる'}).click();
 await page.getByRole('button',{name:/^2026-10-04 /}).click();
 await expect(page.getByRole('heading',{name:'10月4日 日曜日'})).toBeVisible();
 await expect(page.getByText('前日 23:30 – 00:30')).toBeVisible();
 await page.getByRole('button',{name:/^2026-10-15 /}).click();
 await expect(page.getByText('予定はありません')).toBeVisible();
 await page.getByRole('button',{name:'翌月',exact:true}).click();
 await expect(page.getByRole('heading',{name:'2026年 11月'})).toBeVisible();
 await page.getByRole('button',{name:'今日',exact:true}).click();
 await expect(page.locator('.event-card')).toHaveCount(5);
 await page.getByRole('button',{name:'日',exact:true}).click();
 await expect(page.locator('.month-grid')).toHaveCount(0);
 await page.screenshot({path:`test-results/day-${info.project.name}.png`,fullPage:true});
 await page.getByRole('button',{name:'翌日',exact:true}).click();
 await expect(page.getByRole('heading',{name:'10月4日 日曜日'})).toBeVisible();
 expect(errors).toEqual([]);
});
test('preferences, missing state and failure retain cached samples',async({page})=>{
 await page.goto('/');await expect(page.locator('.event-card')).toHaveCount(5);
 await page.getByRole('button',{name:'設定',exact:true}).click();
 await page.getByLabel('テーマ').selectOption('dark');
 await page.getByLabel('文字サイズ').selectOption('large');
 await page.getByLabel('週の始まり').selectOption('0');
 await page.getByLabel('デモの取得状態').selectOption('not_configured');
 await page.getByRole('button',{name:'設定を閉じる'}).click();
 await expect(page.getByText('この日の予定は未取得です')).toBeVisible();
 await expect(page.getByText('予定はありません')).toHaveCount(0);
 await page.getByRole('button',{name:'設定',exact:true}).click();await page.getByLabel('デモの取得状態').selectOption('auth_required');await page.getByRole('button',{name:'設定を閉じる'}).click();
 await expect(page.locator('.event-card')).toHaveCount(5);await expect(page.getByRole('status')).toContainText('再認証が必要');
 await page.reload();await expect(page.locator('.calendar-app')).toHaveClass(/dark large/);await expect(page.locator('.event-card')).toHaveCount(5);
 await page.route('**/api/events?*',route=>route.abort());await page.getByRole('button',{name:'予定を更新',exact:true}).click();
 await expect(page.getByRole('status')).toContainText('オフライン');await expect(page.locator('.event-card')).toHaveCount(5);
 await page.getByRole('button',{name:'翌月',exact:true}).click();await expect(page.locator('.event-card')).toHaveCount(0);await expect(page.getByText('予定はありません')).toHaveCount(0);
});
test('fixed injected clock preserves a manually selected day',async({page})=>{
 await page.clock.install({time:new Date('2026-10-03T14:20:00+09:00')});
 // This server uses a fixed injected clock; verify day navigation never changes its today marker.
 await page.goto('/');await expect(page.locator('.event-card')).toHaveCount(5);
 await page.getByRole('button',{name:/^2026-10-02 /}).click();await page.clock.fastForward(24*60*60*1000);
 await expect(page.getByRole('heading',{name:'10月2日 金曜日'})).toBeVisible();
 await page.getByRole('button',{name:'今日',exact:true}).click();await expect(page.getByRole('heading',{name:'10月3日 土曜日'})).toBeVisible();
});

test('week timeline crosses months, separates all-day and midnight, and supports touch',async({page},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');await expect(page.locator('.event-card')).toHaveCount(5);
 await page.getByRole('button',{name:'設定',exact:true}).click();await page.getByLabel('週の始まり').selectOption('1');await page.getByRole('button',{name:'設定を閉じる'}).click();
 const requests:string[]=[];page.on('request',r=>{if(r.url().includes('/api/events?'))requests.push(r.url());});
 await page.getByRole('button',{name:'週',exact:true}).click();
 await expect(page.getByRole('heading',{name:'2026年 9月28日 – 10月4日'})).toBeVisible();
 await expect(page.locator('.all-day-event')).toHaveCount(1);
 await expect(page.locator('.week-event').filter({hasText:'日付跨ぎ'})).toHaveCount(2);
 expect(requests.some(r=>r.includes('month=2026-09'))).toBe(true);
 expect(requests.some(r=>r.includes('month=2026-10'))).toBe(true);
 await expect(page.locator('.week-header')).toBeVisible();
 await page.screenshot({path:`test-results/week-${info.project.name}.png`,fullPage:true});
 await page.locator('.week-scroll').evaluate(el=>el.scrollTop=0);
 await page.screenshot({path:`test-results/week-midnight-${info.project.name}.png`,fullPage:true});
 await page.getByRole('button',{name:'翌週',exact:true}).click();
 await expect(page.getByRole('heading',{name:'2026年 10月5日 – 10月11日'})).toBeVisible();
 await expect(page.locator('.all-day-event').filter({hasText:'複数日'})).toHaveCount(3);
 await page.screenshot({path:`test-results/week-multiday-${info.project.name}.png`,fullPage:true});
 await page.locator('.all-day-event').first().click();await expect(page.getByRole('dialog')).toBeVisible();
 await page.getByRole('button',{name:'詳細を閉じる'}).click();
 await page.getByRole('button',{name:'設定',exact:true}).click();
 await page.getByLabel('起動時の表示').selectOption('week');await page.getByLabel('週の始まり').selectOption('0');
 await page.getByLabel('文字サイズ').selectOption('large');await page.getByRole('button',{name:'設定を閉じる'}).click();
 await expect(page.getByRole('heading',{name:'2026年 10月4日 – 10月10日'})).toBeVisible();
 await page.reload();await expect(page.getByRole('button',{name:'週',exact:true})).toHaveAttribute('aria-pressed','true');
 const client=await page.context().newCDPSession(page);await client.send('Emulation.setTouchEmulationEnabled',{enabled:true});
 await page.getByRole('button',{name:'翌週',exact:true}).tap();
 await expect(page.getByRole('heading',{name:'2026年 10月4日 – 10月10日'})).toBeVisible();
 await page.locator('.all-day-event').first().tap();await expect(page.getByRole('dialog')).toBeVisible();
 await page.getByRole('button',{name:'詳細を閉じる'}).tap();
 const scroll=page.locator('.week-scroll');await scroll.evaluate(el=>el.scrollTop=0);
 const box=await scroll.boundingBox();if(!box)throw new Error('Missing scroll area');
 await client.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:box.x+100,y:box.y+box.height-50}]});
 await client.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:box.x+100,y:box.y+100}]});
 await client.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
 await expect.poll(()=>scroll.evaluate(el=>el.scrollTop)).toBeGreaterThan(0);
 expect(errors).toEqual([]);
 const size=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));expect(size.scroll).toBeLessThanOrEqual(size.width);
});

test('cross-month copies are deduplicated and failed new weeks stay unacquired',async({page})=>{
 const event={id:'boundary',calendarId:'test',calendarName:'合成',title:'跨月の合成予定',color:'#1a73e8',kind:'allDay',start:'2026-09-30',end:'2026-10-02'};
 await page.route('**/api/events?*',route=>route.fulfill({json:{events:[event],complete:true,fetchedAt:'2026-10-03T05:20:00Z',state:'fresh',synthetic:true}}));
 await page.goto('/');await page.getByRole('button',{name:'週',exact:true}).click();
 await expect(page.locator('.all-day-event')).toHaveCount(2);
 await expect(page.locator('.all-day-event').first()).toContainText('→');
 await expect(page.locator('.all-day-event').last()).toContainText('←');
 await page.unroute('**/api/events?*');await page.route('**/api/events?*',route=>route.abort());
 await page.getByRole('button',{name:'予定を更新',exact:true}).click();
 await expect(page.getByRole('status')).toContainText('オフライン');await expect(page.locator('.all-day-event')).toHaveCount(2);
 await page.getByRole('button',{name:'翌週',exact:true}).click();
 await expect(page.locator('.all-day-event')).toHaveCount(0);await expect(page.locator('.week-header .unfetched')).toHaveCount(7);
});

test('Sunday defaults migrate saved settings and allow subsequent Monday choice',async({page})=>{
 await page.addInitScript(()=>{if(!localStorage.getItem('pi-calendar-preferences'))localStorage.setItem('pi-calendar-preferences',JSON.stringify({theme:'light',weekStart:1,scale:'normal',startupView:'month'}));});
 await page.goto('/');await expect(page.locator('.weekdays span').first()).toHaveText('日');
 await expect(page.locator('.day-cell').first()).toHaveAttribute('aria-label',/^2026-09-27/);
 await page.getByRole('button',{name:'週',exact:true}).click();
 await expect(page.getByRole('heading',{name:'2026年 9月27日 – 10月3日'})).toBeVisible();
 await page.getByRole('button',{name:'設定',exact:true}).click();await expect(page.getByLabel('テーマ')).toHaveValue('auto');
 await page.getByLabel('週の始まり').selectOption('1');await page.getByRole('button',{name:'設定を閉じる'}).click();
 await page.reload();await expect(page.locator('.weekdays span').first()).toHaveText('月');
});

test('manual refresh shows progress, new events and failure retains samples',async({page})=>{
 await page.goto('/');await expect(page.locator('.event-card')).toHaveCount(5);
 let release!:()=>void;const wait=new Promise<void>(resolve=>{release=resolve;});
 await page.route('**/api/events?*',async route=>{await wait;await route.fulfill({json:{events:[{id:'updated',calendarId:'test',calendarName:'合成',color:'#1a73e8',title:'手動更新後の予定',kind:'allDay',start:'2026-10-03',end:'2026-10-04'}],complete:true,fetchedAt:'2026-10-03T05:21:00Z',state:'fresh',synthetic:true}});});
 await page.getByRole('button',{name:'予定を更新',exact:true}).tap();
 await expect(page.getByRole('button',{name:'更新中…'})).toBeDisabled();
 await expect(page.locator('.event-card')).toHaveCount(5);
 release();await expect(page.locator('.event-card')).toHaveCount(1);await expect(page.getByRole('status')).toContainText('予定を更新しました');
 await expect(page.locator('.event-card')).toContainText('手動更新後の予定');
 await page.unroute('**/api/events?*');await page.route('**/api/events?*',route=>route.abort());
 await page.getByRole('button',{name:'予定を更新',exact:true}).tap();
 await expect(page.getByRole('status')).toContainText('更新できませんでした');await expect(page.locator('.event-card')).toContainText('手動更新後の予定');
});

test('event content scrolls with wheel, mouse drag and touch without opening details',async({page},info)=>{
 const events=Array.from({length:20},(_,i)=>({id:`scroll-${i}`,calendarId:'test',calendarName:'合成',color:'#1a73e8',title:`スクロール確認 ${i+1}`,kind:'allDay',start:'2026-10-03',end:'2026-10-04'}));
 await page.route('**/api/events?*',route=>route.fulfill({json:{events,complete:true,fetchedAt:'2026-10-03T05:20:00Z',state:'fresh',synthetic:true}}));
 await page.goto('/');await expect(page.locator('.event-card')).toHaveCount(20);
 const list=page.locator('.agenda-list');await page.locator('.event-card').first().hover();await page.mouse.wheel(0,250);
 await expect.poll(()=>list.evaluate(el=>el.scrollTop)).toBeGreaterThan(0);
 await list.evaluate(el=>el.scrollTop=0);
 const card=await page.locator('.event-card').first().boundingBox();if(!card)throw new Error('Missing card');
 await page.mouse.move(card.x+50,card.y+card.height-15);await page.mouse.down();await page.mouse.move(card.x+50,card.y+10,{steps:10});await page.mouse.up();
 await expect.poll(()=>list.evaluate(el=>el.scrollTop)).toBeGreaterThan(0);await expect(page.getByRole('dialog')).toHaveCount(0);
 await list.evaluate(el=>el.scrollTop=0);
 const client=await page.context().newCDPSession(page);
 await client.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:card.x+50,y:card.y+card.height-15}]});
 await client.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:card.x+50,y:card.y+10}]});
 await client.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
 await expect.poll(()=>list.evaluate(el=>el.scrollTop)).toBeGreaterThan(0);await expect(page.getByRole('dialog')).toHaveCount(0);
 await page.getByRole('button',{name:'設定',exact:true}).tap();await page.getByLabel('テーマ').selectOption('dark');await page.getByRole('button',{name:'設定を閉じる'}).tap();
 await expect(page.locator('.calendar-app')).toHaveClass(/dark/);await page.screenshot({path:`test-results/features-dark-${info.project.name}.png`,fullPage:true});
});
